# Generated by Django 5.2.4 on 2025-07-12 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_hours',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='shop',
            name='openning_hours',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
