# Generated by Django 5.2.4 on 2025-07-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_shop_address_shop_closing_hours_shop_openning_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='openning_hours',
            new_name='opening_hours',
        ),
    ]
