# Generated by Django 5.2.4 on 2025-07-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_openning_hours_shop_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
