# Generated by Django 5.2.4 on 2025-07-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
