# Generated by Django 5.2.4 on 2025-07-14 04:00

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_shop_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_shop_name_ci'),
        ),
    ]
