# Generated by Django 5.2.3 on 2025-07-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_shop_name_shop_uniq_shop_name_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='closing_day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='fri', help_text='Last weekday shop is open', max_length=3),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', help_text='First weekday shop is open', max_length=3),
        ),
    ]
