# Generated by Django 5.2.3 on 2025-07-27 20:00

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_shop_closing_day_shop_opening_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='closing_day',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='opening_day',
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default=['0', '1', '2', '3', '4'], help_text='Select weekdays when the shop is open', max_length=20),
        ),
    ]
