# Generated by Django 5.2.3 on 2025-07-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_shop_closing_day_remove_shop_opening_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='opening_days',
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='fri', max_length=3),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_day',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3),
        ),
    ]
