# Generated by Django 5.2.4 on 2025-07-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_appointment_duration_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Confirmed', max_length=10),
        ),
    ]
