# Generated by Django 5.2.4 on 2025-08-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_appointment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='desc',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
