# Generated by Django 5.2.4 on 2025-08-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_shop_desc_shop_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='desc',
            new_name='description',
        ),
    ]
