# Generated by Django 5.2.4 on 2025-08-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_rename_desc_shop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(
            max_length=120,
            allow_unicode=True,
            blank=True,
            null=True,         
            default=None,      
            unique=False,      
            ),
        ),
    ]
